//! HFS name comparison and Unicode tables.
//!
//! Mining reference: Apple `core/UnicodeWrappers.c` (`FastUnicodeCompare`,
//! `UnicodeBinaryCompare`) and `core/UCStringCompareData.h` (the case folding
//! tables). `core/hfs_catalog.c` (`CompareExtendedCatalogKeys`,
//! `cat_binarykeycompare`) is what actually calls them.
//!
//! The rules for *which* comparator a volume uses, and why they are subtler than
//! "HFSX means case-sensitive", are documented in [`compare`].
//!
//! The tables are generated by `tools/genucdtables.py` and are derived data, so
//! they stay under APSL-1.2.

pub mod compare;
pub mod tables;

pub use compare::{fast_unicode_compare, unicode_binary_compare, Comparator, Ordering};
