#!/usr/bin/env bash
#
# Generate one manifest per generated image from ground truth.
#
# The point of this script is that the manifest is never written by hand from
# memory. Every fact under [volume] and [forks] comes from the volume header via
# `hfsinspect --json`, and the [verify] block comes from running the independent
# Apple checker. That way a bug in the Rust parser cannot end up redefining what
# the parser is supposed to produce: the manifest is captured before the parser
# is consulted, and the tests then compare the two.
#
# Usage:
#   tools/genmanifests.sh
#
# Requires the crate to be built (cargo build) so hfsinspect exists.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${REPO_ROOT}"

IMG_DIR="tests/images/generated"
MAN_DIR="tests/images/manifests"
FSCK="${FSCK:-/usr/sbin/fsck.hfsplus}"

[[ -x ${FSCK} ]] || FSCK=$(command -v fsck.hfsplus || true)

cargo build --quiet --bin hfsinspect

mkdir -p "${MAN_DIR}"

for img in "${IMG_DIR}"/*.img; do
  name=$(basename "${img}" .img)
  printf 'generating %s ... ' "${name}"

  # hfsinspect exits 2 when an image fails to parse, which is itself a result we
  # want to record, so the non-zero status must not abort the script.
  json=$(./target/debug/hfsinspect --json "${img}" || true)
  summary=$(python3 - "${json}" "${name}" "${img}" "${FSCK}" <<'PYEOF'
import hashlib, json, subprocess, sys

doc, name, img, fsck = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
d = json.loads(doc)

# Ground truth from the independent Apple checker.
verdict, output = "UNKNOWN", ""
if fsck:
    p = subprocess.run([fsck, img], capture_output=True, text=True)
    output = p.stdout + p.stderr
    verdict = "OK" if "appears to be OK" in output else "FAIL"

def f(k):
    for entry in d["forks"]:
        if entry["name"] == k:
            return entry
    raise KeyError(k)

with open(img, "rb") as fh:
    digest = hashlib.sha256(fh.read()).hexdigest()

# A volume outside this project's scope still gets a manifest: the requirement
# is that it be refused structurally, and that has to be stated and tested.
if not d.get("ok"):
    rejected = f'''# Generated by tools/genmanifests.sh -- do not hand-edit.
name = "{name}"
description = "Classic HFS volume, outside this project's scope."
filesystem = "HFS"
journaled = false
case_sensitive = false

[source]
type = "generated"
tool = "mkfs.hfsplus"
tool_version = "540.1.linux3"
tool_licence = "APSL-2.0"
command = "mkfs.hfsplus -h -v ClassicVolume {img}"
image = "{img}"
sha256_informational = "{digest}"

[features]
# Not applicable: nothing is parsed from this image beyond its signature.
catalog_btree = false
extents_overflow_btree = false
attributes_btree = false
journal = false

[expect]
# "mount" | "mount-readonly" | "reject-cleanly"
outcome = "reject-cleanly"
# Structural error the parser must return instead of panicking.
expected_error = "unrecognised volume signature"
note = "classic HFS (0x4244) is a real HFS family signature but is not HFS+ or HFSX; it must be refused, never misparsed"

[verify]
checker = "fsck.hfsplus"
checker_version = "540.1.linux3-6build1"
verdict = "{verdict}"
checker_output_contains = "appears to be OK"
'''
    print(rejected, end="")
    raise SystemExit(0)

journaled = d["journaled"]
# hfsprogs -s selects HFSX by signature; the case sensitivity of a volume is
# really decided by the catalog B-tree's keyCompareType, which is not parsed
# yet, so the manifest records the signature-derived expectation.
case_sensitive = d["filesystem"] == "HFSX"
fs = d["filesystem"]


def block(k):
    return (
        f"[forks.{k}]\n"
        f"logical_size = {f(k)['logical_size']}\n"
        f"total_blocks = {f(k)['total_blocks']}\n\n"
    )

# Classic HFS is a real HFS family signature but is outside this project's
# scope: the parser must recognise it and refuse it structurally, never
# misparse it as HFS+ and never panic.
if fs == "HFS":
    outcome = "reject-cleanly"
    expected_error = "unrecognised volume signature"
    note = "classic HFS (0x4244) is recognised but not implemented"
else:
    outcome = "mount-readonly"
    expected_error = ""
    note = "HFS+/HFSX read-only support is the milestone under test"

# Most images are pure mkfs.hfsplus output. One is not: journal-with-files has
# real files added afterwards by tools/mkfiles.py, and its provenance must say so
# rather than credit mkfs.hfsplus for content that formatter never wrote.
if name == "journal-with-files":
    source_tool = "mkfs.hfsplus, then tools/mkfiles.py"
    source_command = ("mkfs.hfsplus -J -v Journaled "
                      "tests/images/generated/journaled-hfsplus.img, then "
                      "tools/mkfiles.py")
    description = ("Journaled volume with files added by tools/mkfiles.py: "
                   "fragmented extents and a symlink.")
else:
    source_tool = "mkfs.hfsplus"
    source_command = "see tools/genimages.sh"
    description = "Generated with mkfs.hfsplus; see tests/images/README.md."

toml = f'''# Generated by tools/genmanifests.sh -- do not hand-edit [volume]/[forks].
name = "{name}"
description = "{description}"
filesystem = "{fs}"
journaled = {str(journaled).lower()}
case_sensitive = {str(case_sensitive).lower()}

[source]
type = "generated"
tool = "{source_tool}"
tool_version = "540.1.linux3"
tool_licence = "APSL-2.0"
command = "{source_command}"
image = "{img}"
# Images embed creation timestamps, so this digest changes on regeneration.
# It is recorded for provenance, not used as a byte-exact test fixture.
sha256_informational = "{digest}"

[volume]
block_size = {d['block_size']}
total_blocks = {d['total_blocks']}
free_blocks = {d['free_blocks']}
volume_bytes = {d['volume_bytes']}
next_catalog_id = {d['next_catalog_id']}
file_count = {d['file_count']}
folder_count = {d['folder_count']}
attributes = "0x{d['attributes']:08x}"
unmounted = {str(d['clean']).lower()}
journal_info_block = {d['journal_info_block']}
expanded_times = {str(d['expanded_times']).lower()}

{block('allocationFile')}{block('extentsFile')}{block('catalogFile')}{block('attributesFile')}{block('startupFile')}
[features]
catalog_btree = {str(f('catalogFile')['logical_size'] > 0).lower()}
extents_overflow_btree = {str(f('extentsFile')['logical_size'] > 0).lower()}
attributes_btree = {str(f('attributesFile')['logical_size'] > 0).lower()}
journal = {str(journaled).lower()}
# Not yet determinable from the volume header alone; see README.
unicode = true
hard_links = false
directory_hard_links = false
resource_forks = false
xattrs = false
finder_info = false
compression = false
sparse_files = false

[expect]
# "mount" | "mount-readonly" | "reject-cleanly"
outcome = "{outcome}"
# Structural error the parser must return instead of panicking.
expected_error = "{expected_error}"
note = "{note}"

[verify]
checker = "fsck.hfsplus"
checker_version = "540.1.linux3-6build1"
verdict = "{verdict}"
checker_output_contains = "appears to be OK"
'''


print(toml, end="")
PYEOF
)
  echo "$summary" > "${MAN_DIR}/${name}.toml"
  echo "done"
done

echo
echo "wrote $(ls -1 "${MAN_DIR}"/*.toml | wc -l) manifests to ${MAN_DIR}"
